language: elixir
notifications:
  recipients:
    - eduardo@gurgel.me
elixir:
  - 1.0.3
  - 1.0.4
otp_release:
  - 17.0
  - 17.1
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
